/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#fed639",
        secondary: "#d2bbff",
        tertiary: "#fff5de",
        "on-surface-variant": "#b9cacb",
        "on-tertiary": "#3b2f00",
        surface: "#051424",
        "inverse-on-surface": "#233143",
        "inverse-primary": "#006970",
        "surface-dim": "#051424",
        "on-secondary": "#3f008e",
        "secondary-fixed": "#eaddff",
        "surface-container-high": "#1c2b3c",
        "surface-container-lowest": "#010f1f",
        "secondary-fixed-dim": "#d2bbff",
        "on-error-container": "#ffdad6",
        "primary-container": "#00f0ff",
        "on-tertiary-fixed": "#231b00",
        "on-secondary-fixed": "#25005a",
        "secondary-container": "#6001d1",
        "on-primary-container": "#006970",
        "surface-bright": "#2c3a4c",
        "inverse-surface": "#d4e4fa",
        "surface-variant": "#273647",
        primary: "#dbfcff",
        "surface-container-highest": "#273647",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#eac324",
        "tertiary-fixed": "#ffe179",
        "surface-container-low": "#0d1c2d",
        "on-primary-fixed": "#002022",
        "primary-fixed-dim": "#00dbe9",
        "primary-fixed": "#7df4ff",
        error: "#ffb4ab",
        background: "#051424",
        "surface-container": "#122131",
        "on-primary": "#00363a",
        "surface-tint": "#00dbe9",
        "on-background": "#d4e4fa",
        outline: "#849495",
        "on-secondary-fixed-variant": "#5a00c6",
        "on-primary-fixed-variant": "#004f54",
        "on-secondary-container": "#c9aeff",
        "outline-variant": "#3b494b",
        "on-tertiary-container": "#715d00",
        "on-surface": "#d4e4fa",
        "on-tertiary-fixed-variant": "#554500",
        "error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-padding": "24px",
        "card-gap": "12px",
        gutter: "16px",
        "stack-loose": "16px",
        unit: "4px",
        "stack-tight": "4px",
      },
      fontFamily: {
        "headline-sm": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "data-mono": ["13px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
